[project]
name = "foam-web"
version = "0.1.0"
description = "A simple web server for browsing and rendering Markdown files"
requires-python = ">=3.12"
dependencies = [
    "hupper",
    "livereload",
    "markdown-it-py",
    "mdit-py-plugins",
    "pygments",
    "typer",
]

[project.scripts]
foam-web = "foam_web.cli:main"

[build-system]
requires = ["uv_build>=0.6.6,<0.7"]
build-backend = "uv_build"
